export const MAX_PLAYERS = 20;
export const SESSION_EXPIRY_MS = 7_200_000;
export const ROOM_CODE_LENGTH = 4;
export const ROOM_CODE_CHARSET = "23456789";
export const MIN_INITIATIVE = -10;
export const MAX_INITIATIVE = 40;
export const MIN_NAME_LENGTH = 1;
export const MAX_NAME_LENGTH = 50;
export const WS_HEARTBEAT_INTERVAL_MS = 30_000;
export const WS_CLOSE_TIMEOUT_MS = 5_000;

export enum ErrorCode {
  SESSION_NOT_FOUND = "SESSION_NOT_FOUND",
  SESSION_FULL = "SESSION_FULL",
  NAME_TAKEN = "NAME_TAKEN",
  UNAUTHORIZED = "UNAUTHORIZED",
  PLAYER_NOT_FOUND = "PLAYER_NOT_FOUND",
  INVALID_INITIATIVE = "INVALID_INITIATIVE",
  ROOM_CODE_COLLISION = "ROOM_CODE_COLLISION",
  INVALID_NAME = "INVALID_NAME",
  SESSION_EXPIRED = "SESSION_EXPIRED",
}

export type SessionStatus = "WAITING" | "ACTIVE" | "COMPLETED";
