name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency: deploy-group
    steps:
      - uses: actions/checkout@v4
      - uses: bervProject/railway-deploy@master
        with:
          railway_token: ${{ secrets.RAILWAY_TOKEN }}
